### ISSUE TITLE
 FileNotFoundError: [WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by jsdpr15** [Ronald-Saunfe/LMS#1]
Sir when i run your code i get this error
how to fix it 
" FileNotFoundError: [WinError 2] The system cannot find the file specified"

**Comment by Ronald-Saunfe** [comment]
fixed

**Comment by jsdpr15** [comment]
Sir did you make any video of live coding for this app
Please share if yes

**Comment by Ronald-Saunfe** [comment]
Nop i wish i could, but this was my first application. I had no knowledge of code modulation when creating it. The code is poorly written bare with me

**Comment by jsdpr15** [comment]
Ohh oke sir
I am Little bit confused that how you automated hiding mechanism so I ask

**Comment by jsdpr15** [comment]
Sir, can you share code of menu only please i want to learn its woring

**Comment by Ronald-Saunfe** [comment]
what hiding mechanism?
